### PR TITLE
copied .eslintrc.js fom OBE and solving version conflicts

### LINKED ISSUE #161: Fix linter
**Is your feature request related to a problem? Please describe.**
We should ensure the linter is working correctly, so we don't have to deal with changes between styles.

**Describe the solution you'd like**
-`yarn lint` command runs successfully in the project

### PR DESCRIPTION
**Pull request by Viterbo**
# Description
Fixed Linter config.

Fixes #161
the `yarn lint` command now works.

## Changes
The `.eslintrc.js` file was replaced with [the one taken from the OBE project](https://github.com/telosnetwork/open-block-explorer/blob/master/.eslintrc.js) and some package versions were changed to avoid conflicts between them.

## Visual Code config
To enable Linter on VC you need to install the following extensions:
- ESLint (dbaeumer.vscode-eslint)
- Prettier (esbenp.prettier-vscode)

## Screenshots
Now we have some new issues to fix XD

image

image

### CODE REVIEW

**Review by donnyquixotic — APPROVED** [review]

**Review by karynemayer — COMMENTED** [review]
@Viterbo I was under the impression that we would use only eslint and not prettier anymore. I don't have an opinion, but wanted to make sure that we're choosing to keep and use prettier before approving it.

**Comment by Viterbo** [comment]
@DevArtemNuss, this PR was marked as a draft because although is working properly (it doesn't crash) is causing all the code to turn red because it finds many many "errors".

Your mission, if you choose to accept it, is to clone this branch locally and remove one by one all the rules that are generating lots of errors. Also, we decided not to use prettier so it should be removed from the configuration as well.

Do you feel you can do that?

**Review by donnyquixotic — APPROVED** [review]

**Comment by karynemayer** [comment]
@donnyquixotic I would like us to agree on the ESLint rules before merging this.

**Comment by EJSG** [comment]
What is the expected result for this PR, is it that the ESLint package is added to the project, with the intention of adding in / customizing rules later? I see that vue and typescript linting rules are disabled

**Review by donnyquixotic — APPROVED** [review]

**Comment by donnyquixotic** [comment]
> What is the expected result for this PR, is it that the ESLint package is added to the project, with the intention of adding in / customizing rules later? I see that vue and typescript linting rules are disabled

I believe @Viterbo disabled rules due to the amount of errors introduced with the intention of enabling and resolving them one by one afterward. I don't have a strong opinion about whether it's all done in one PR or as follow-up tasking (as long as it's captured)

**Review by EJSG — APPROVED** [review]

**Comment by donnyquixotic** [comment]
@karynemayer @Viterbo @DevArtemNuss let's agree on the rules and either merge this PR so it doesn't linger (and create follow-up issue(s) to immediately address the linting errors or agree to resolve them in this PR.

**Review by donnyquixotic — APPROVED** [review]

**Pull request merged**
